// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcWBAJ2lCy9wOFx-kONqoxkTO9ey0E9Us',
    appId: '1:1013766552572:web:6887e6500b7e8a18da5079',
    messagingSenderId: '1013766552572',
    projectId: 'helmet-858a5',
    authDomain: 'helmet-858a5.firebaseapp.com',
    databaseURL: 'https://helmet-858a5-default-rtdb.firebaseio.com',
    storageBucket: 'helmet-858a5.firebasestorage.app',
    measurementId: 'G-VCMY69XB2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmVVhzEmOEITQUCkoSlTMfG6FB8NpcL8g',
    appId: '1:1013766552572:android:c39cbd72ac8f6704da5079',
    messagingSenderId: '1013766552572',
    projectId: 'helmet-858a5',
    databaseURL: 'https://helmet-858a5-default-rtdb.firebaseio.com',
    storageBucket: 'helmet-858a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-2JFT3p0aiP2Lhw7k2wP-FQb_IAwv4nE',
    appId: '1:1013766552572:ios:859a0dbacb92af0ada5079',
    messagingSenderId: '1013766552572',
    projectId: 'helmet-858a5',
    databaseURL: 'https://helmet-858a5-default-rtdb.firebaseio.com',
    storageBucket: 'helmet-858a5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-2JFT3p0aiP2Lhw7k2wP-FQb_IAwv4nE',
    appId: '1:1013766552572:ios:859a0dbacb92af0ada5079',
    messagingSenderId: '1013766552572',
    projectId: 'helmet-858a5',
    databaseURL: 'https://helmet-858a5-default-rtdb.firebaseio.com',
    storageBucket: 'helmet-858a5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcWBAJ2lCy9wOFx-kONqoxkTO9ey0E9Us',
    appId: '1:1013766552572:web:d711957a07a19efbda5079',
    messagingSenderId: '1013766552572',
    projectId: 'helmet-858a5',
    authDomain: 'helmet-858a5.firebaseapp.com',
    databaseURL: 'https://helmet-858a5-default-rtdb.firebaseio.com',
    storageBucket: 'helmet-858a5.firebasestorage.app',
    measurementId: 'G-FWYEWXNEBK',
  );
}
